append narrator name to the output folder

diff --git a/AAXtoMP3 b/AAXtoMP3
--- a/AAXtoMP3
+++ b/AAXtoMP3
@@ -19,6 +19,7 @@ DEBUG=0                     # Default off, If set extremely verbose output.
 noclobber=0                 # Default off, clobber only if flag is enabled
 continue=0                  # Default off, If set Transcoding is skipped and chapter splitting starts at chapter continueAt.
 continueAt=1                # Optional chapter to continue splitting the chapters.
+appendNarrator=0						# Default off, Append the narrator name to the Folder name. Needs mediainfo
 
 # -----
 # Code tip Do not have any script above this point that calls a function or a binary.  If you do
@@ -59,6 +60,8 @@ while true; do
     --continue        ) continueAt="$2"; continue=1;                                    shift 2 ;;
                       # Compression level
     --level           ) level="$2";                                                     shift 2 ;;
+											# Append Narrator
+		--append-narrator	)	appendNarrator=1;																								shift ;;
                       # Command synopsis.
     -h | --help       ) printf "$usage" $0 ;                                            exit ;;
                       # Standard flag signifying the end of command line processing.
@@ -141,7 +144,7 @@ log() {
 
 # -----
 # Print out what we have already after command line processing.
-debug_vars "Command line options as set" codec extension mode container targetdir completedir auth_code
+debug_vars "Command line options as set" codec extension mode container targetdir completedir auth_code appendNarrator
 
 # ========================================================================
 # Variable validation
@@ -295,6 +298,13 @@ if [ "${level}" != "-1" ]; then
 fi
 
 # -----
+# Check for presence of mediainfo in case the flag --append-narrator is used
+if [[ "${appendNarrator}" == 1 && "x$(type -P mediainfo)" == "x" ]]; then
+	echo "ERROR --append-narator specified, but mediainfo is not in PATH"
+  exit 1
+fi
+
+# -----
 # Clean up if someone hits ^c or the script exits for any reason.
 trap 'rm -r -f "${working_directory}"' EXIT
 
@@ -434,7 +444,11 @@ do
     description=""
     publisher=""
   fi
-
+	# If the flag --append-narrator is used, we append the narrator name to the output dir
+	if [[ "${appendNarrator}" == 1 ]]; then
+		output_directory="${output_directory}"-"${narrator}"
+  	output_file="${output_directory}/${title}.${extension}"
+	fi
   if [[ "${noclobber}" = "1" ]] && [[ -d "${output_directory}" ]]; then
     log "Noclobber enabled but directory '${output_directory}' exists. Exiting to avoid overwriting"
     exit 0
